# Generated by Django 4.2.3 on 2023-07-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0002_file_remove_data_user_remove_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='CSV_Folder')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
