# Generated by Django 4.2.3 on 2023-07-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0003_folder_delete_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Localion',
        ),
        migrations.AddField(
            model_name='data',
            name='Locality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
